dist: simplified scyllamgr_ssl_cert_gen

diff --git a/dist/scripts/scyllamgr_ssl_cert_gen b/dist/scripts/scyllamgr_ssl_cert_gen
--- a/dist/scripts/scyllamgr_ssl_cert_gen
+++ b/dist/scripts/scyllamgr_ssl_cert_gen
@@ -5,35 +5,28 @@ set -e
 KEY_FILE="/var/lib/scylla-manager/scylla_manager.key"
 CRT_FILE="/var/lib/scylla-manager/scylla_manager.crt"
 SUBJECT="/C=US/ST=Scylla/L=Scylla/O=Scylla/OU=Scylla/CN=scylla.com"
-PRESERVE_FILES="keep"
-HAVE_FILES=0
-SILENT="verbose"
-FAIL_MODE="lazy"
 
 print_usage() {
     echo "scyllamgr_ssl_cert_gen --subject <the_subject>"
-    echo "  -s --subject				specify certificate info, default=\"${SUBJECT}\""
-    echo "     --overwrite              regenerate and overwrite the existing certificate files, default is false"
-    echo "     --silent                 suppress error messages, default is false"
-    echo "     --fail-fast              fail as possible when an error happens, default false"
-    echo "  -h --help	    			display help info"
+    echo "  -s --silent                 suppress error messages, default is false"
+    echo "     --subject                specify certificate info, default is '${SUBJECT}'"
+    echo "  -h --help                   display help info"
 }
+
+if [ "`id -u`" -ne 0 ]; then
+    echo "Requires root permission."
+    exit 1
+fi
+
+SILENT=0
 
 while [ $# -gt 0 ]; do
     case "$1" in
-        "--fail-fast")
-            FAIL_MODE="fast"
+        "-s"|"--silent")
+            SILENT=1
             shift 1
             ;;
-        "--silent")
-            SILENT="silent"
-            shift 1
-            ;;
-        "--overwrite")
-            PRESERVE_FILES="overwrite"
-            shift 1
-            ;;
-        "-s"|"--subject")
+        "--subject")
             SUBJECT="$2"
             shift 2
             ;;
@@ -46,39 +39,15 @@ while [ $# -gt 0 ]; do
     esac
 done
 
-if [ "`id -u`" -ne 0 ]; then
-    echo "Requires root permission."
-    exit 1
+
+if [ -f ${KEY_FILE} -o -f ${CRT_FILE} ]; then
+    if [ $SILENT -eq 0 ]; then
+        echo "certificate exists, to recreate run 'rm $KEY_FILE $CRT_FILE' and try again"
+    fi
+    exit 0
 fi
 
-if [ -f ${KEY_FILE} ]; then
-    HAVE_FILES=1
-    if [ "$SILENT" = "verbose" ]; then
-        echo "key '$KEY_FILE' exists, to regenerate please delete it as well as the certificate '$CRT_FILE'"
-    fi
-    if [ "$FAIL_MODE" = "fast" ]; then
-        exit 1
-    fi
-fi
-
-if [ -f ${CRT_FILE} ]; then
-    HAVE_FILES=1
-    if [ "$SILENT" = "verbose" ]; then
-        echo "certificate '$CRT_FILE' exists, to regenerate please delete it as well as the key '$KEY_FILE'"
-    fi
-    if [ "$FAIL_MODE" = "fast" ]; then
-        exit 1
-    fi
-fi
-
-if [ $HAVE_FILES -eq 0 ]; then
-    openssl genrsa -out ${KEY_FILE} 4096
-    openssl req -new -x509 -sha512 -subj "${SUBJECT}" -key ${KEY_FILE} -out ${CRT_FILE} -days 365
-    chown scylla-manager:scylla-manager ${KEY_FILE}
-    chown scylla-manager:scylla-manager ${CRT_FILE}
-elif [ "$PRESERVE_FILES" = "overwrite" ]; then
-    openssl genrsa -out ${KEY_FILE} 4096
-    openssl req -new -x509 -sha512 -subj "${SUBJECT}" -key ${KEY_FILE} -out ${CRT_FILE} -days 365
-    chown scylla-manager:scylla-manager ${KEY_FILE}
-    chown scylla-manager:scylla-manager ${CRT_FILE}
-fi
+openssl genrsa -out ${KEY_FILE} 4096
+openssl req -new -x509 -sha512 -subj "${SUBJECT}" -key ${KEY_FILE} -out ${CRT_FILE} -days 365
+chown scylla-manager:scylla-manager ${KEY_FILE}
+chown scylla-manager:scylla-manager ${CRT_FILE}
