internal/ssh: revert to 1.4
This reverts code to the standard ssh tunnelling as we know from the
previous versions of Scylla Manager. Now scyllaclient is using the agent.

Signed-off-by: Michał Matczuk <michal@scylladb.com>

diff --git a/dist/scripts/scyllamgr_ssh_setup b/dist/scripts/scyllamgr_ssh_setup
--- a/dist/scripts/scyllamgr_ssh_setup
+++ b/dist/scripts/scyllamgr_ssh_setup
@@ -27,12 +27,13 @@ HOST=""
 SSH_USER=""
 SSH_IDENTITY_FILE=""
 SSH_CONFIG_FILE=""
-SSH_OPTS="-q -o BatchMode=yes -o ConnectTimeout=5 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"
 
 MANAGER_USER="scylla-manager"
 SINGLE_NODE=0
 
 OUTPUT="/dev/null"
+CURL_OPTS="-sS -f -o /dev/null"
+SSH_OPTS="-q -o BatchMode=yes -o ConnectTimeout=5 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"
 
 while [[ $# > 0 ]]; do
     case "$1" in
@@ -58,6 +59,7 @@ while [[ $# > 0 ]]; do
             ;;
         "--debug")
             OUTPUT=/dev/stderr
+            CURL_OPTS+=" -v"
             SSH_OPTS+=" -v"
             shift 1
             ;;
@@ -154,9 +156,7 @@ fi
 
 # Load manager SSH public key
 
-declare -r MANAGER_SHELL="/var/lib/${MANAGER_USER}/bin/agent"
-declare -r MANAGER_PUBLIC_KEY=$(<"${MANAGER_IDENTITY_FILE}.pub")
-declare -r MANAGER_PUBLIC_KEY_WITH_OPTIONS="no-agent-forwarding,no-port-forwarding,no-X11-forwarding ${MANAGER_PUBLIC_KEY}"
+MANAGER_PUBLIC_KEY=$(<"${MANAGER_IDENTITY_FILE}.pub")
 
 # Distribute SSH keys and create users
 
@@ -168,24 +168,12 @@ for host in ${HOSTS}; do
     if ssh ${ROOT_SSH_OPTS} "${SSH_USER}${host}" &> "${OUTPUT}" sudo su - << EOF
     set -eux -o pipefail
 
-    # Create system user and group
-    getent group "${MANAGER_USER}"  || /usr/sbin/groupadd -r "${MANAGER_USER}"
-    getent passwd "${MANAGER_USER}" || /usr/sbin/useradd  -g "${MANAGER_USER}" -d "/var/lib/${MANAGER_USER}" -r "${MANAGER_USER}"
-
-    # Set scylla user ID (alias)
-    /usr/sbin/usermod -ou \$(id -u scylla) "${MANAGER_USER}"
-
-    # TODO: install agent from a pkg
-
-    # Set agent as a shell
-    chsh -s /usr/bin/scylla-manager-agent "${MANAGER_USER}"
-
     # Add public key to authorized_keys
     mkdir -p "/var/lib/${MANAGER_USER}/.ssh"
-    echo -e "# Added by Scylla Manager\n${MANAGER_PUBLIC_KEY_WITH_OPTIONS}" > "/var/lib/${MANAGER_USER}/.ssh/authorized_keys"
+    echo -e "# Added by Scylla Manager\n${MANAGER_PUBLIC_KEY}" > "/var/lib/${MANAGER_USER}/.ssh/authorized_keys"
 
-    # Fix file ownership
-    chown -R "${MANAGER_USER}:${MANAGER_USER}" "/var/lib/${MANAGER_USER}"
+    # Set owner to manager user
+    chown -R "${MANAGER_USER}:${MANAGER_USER}" "/var/lib/${MANAGER_USER}/.ssh"
 EOF
     then
         echo "${host}	OK"
@@ -202,11 +190,17 @@ if fuser -s -n tcp ${API_LOCAL_PORT}; then
 fi
 
 for host in ${HOSTS}; do
-    if ssh ${SSH_OPTS} "${MANAGER_USER}@${host}" -i "${MANAGER_IDENTITY_FILE}" <<< $'GET /storage_service/cluster_name HTTP/1.1\r\n' &> ${OUTPUT}; then
-        echo "${host}	OK"
+    if ! ssh -i "${MANAGER_IDENTITY_FILE}" -N -f ${SSH_OPTS} -L ${API_LOCAL_PORT}:0.0.0.0:${API_REMOTE_PORT} "${MANAGER_USER}@${host}" &> ${OUTPUT}; then
+        echo "${host}	SSH FAILED"
+        ret=1
     else
-        echo "${host}	FAILED"
-            ret=1
+        if curl ${CURL_OPTS} "localhost:${API_LOCAL_PORT}/storage_service/cluster_name" &> ${OUTPUT}; then
+            echo "${host}	OK"
+        else
+            echo "${host}	FAILED"
+                ret=1
+        fi
+        fuser -s -n tcp ${API_LOCAL_PORT} -k -15 ||:
     fi
 done
 
