dist/scripts: add support in ssh test script for fallback to IP
Fixes #846

Signed-off-by: Michał Matczuk <michal@scylladb.com>

diff --git a/dist/scripts/scyllamgr_ssh_test b/dist/scripts/scyllamgr_ssh_test
--- a/dist/scripts/scyllamgr_ssh_test
+++ b/dist/scripts/scyllamgr_ssh_test
@@ -5,17 +5,22 @@
 
 set -eu -o pipefail
 
-SSH_LOCAL_PORT="10010"
+OUTPUT=/dev/null
+
 SSH_USER="scylla-manager"
 SSH_IDENTITY_FILE=""
 SSH_OPTS="-q -o BatchMode=yes -o ConnectTimeout=5 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"
+
+API_LOCAL_PORT="10010"
+API_REMOTE_PORT="10000"
+API_TEST_URL="/storage_service/cluster_name"
 
 CURL_OPTS="-sS -f -o /dev/null"
 
 print_usage() {
     echo "scyllamgr_ssh_test -u <ssh username> -i <path to ssh private key> HOST..."
     echo "  -i --identity-file			path to identity file containing SSH private key"
-    echo "  -p --local-port			local port used by the script for SSH tunneling, default ${SSH_LOCAL_PORT}"
+    echo "  -p --local-port			local port used by the script for SSH tunneling, default ${API_LOCAL_PORT}"
     echo "  -u --user				SSH user name used to connect to hosts, default ${SSH_USER}"
     echo "  -v --verbose				display debug info"
 }
@@ -31,10 +36,11 @@ while [[ $# > 0 ]]; do
             shift 2
             ;;
         "-p"|"--local-port")
-            SSH_LOCAL_PORT="$2"
+            API_LOCAL_PORT="$2"
             shift 2
             ;;
         "-v"|"--verbose")
+            OUTPUT=/dev/stderr
             SSH_OPTS+=" -v"
             CURL_OPTS+=" -v"
             shift 1
@@ -74,22 +80,27 @@ if [[ ! -f "${SSH_IDENTITY_FILE}" || ! -r "${SSH_IDENTITY_FILE}" ]]; then
     exit 1
 fi
 
-if fuser -s -n tcp ${SSH_LOCAL_PORT}; then
-    echo "port ${SSH_LOCAL_PORT} is used"
+if fuser -s -n tcp ${API_LOCAL_PORT}; then
+    echo "port ${API_LOCAL_PORT} is used"
     exit 1
 fi
 
 ret=0
 
 for host in $@; do
-    if ssh -i "${SSH_IDENTITY_FILE}" -N -f ${SSH_OPTS} -L ${SSH_LOCAL_PORT}:localhost:10000 "${SSH_USER}@${host}" \
-    && curl ${CURL_OPTS} "localhost:${SSH_LOCAL_PORT}/storage_service/cluster_name"; then
-        echo "${host}	OK"
+    if ! ssh -i "${SSH_IDENTITY_FILE}" -N -f ${SSH_OPTS} -L ${API_LOCAL_PORT}:localhost:${API_REMOTE_PORT} "${SSH_USER}@${host}"; then
+        echo "${host}	FAILED TO SSH"
     else
-        echo "${host}	FAILED"
-        ret=1
+        if curl ${CURL_OPTS} "${host}:${API_REMOTE_PORT}${API_TEST_URL}" &> ${OUTPUT}; then
+            echo "${host}	WARNING - host exposes Scylla API"
+        elif curl ${CURL_OPTS} "localhost:${API_LOCAL_PORT}${API_TEST_URL}" &> ${OUTPUT}; then
+            echo "${host}	OK"
+        else
+            echo "${host}	FAILED"
+                ret=1
+        fi
+        fuser -s -n tcp ${API_LOCAL_PORT} -k -15 ||:
     fi
-    fuser -s -n tcp ${SSH_LOCAL_PORT} -k -15 ||:
 done
 
 exit ${ret}
