dist: added file permission validation to ssh setup scripts
Fixes #626

diff --git a/dist/scripts/scyllamgr_ssh_setup b/dist/scripts/scyllamgr_ssh_setup
--- a/dist/scripts/scyllamgr_ssh_setup
+++ b/dist/scripts/scyllamgr_ssh_setup
@@ -74,14 +74,26 @@ if [ -z ${SSH_IDENTITY_FILE} ]; then
     exit 1
 fi
 
-if [ -z ${MANAGER_USER} ]; then
+if [ ! -f "${SSH_IDENTITY_FILE}" -o ! -r "${SSH_IDENTITY_FILE}" ]; then
+    echo -e "cannot read file ${SSH_IDENTITY_FILE}\n"
+    print_usage
+    exit 1
+fi
+
+if [ -z "${MANAGER_USER}" ]; then
     echo -e "missing --manager-user\n"
     print_usage
     exit 1
 fi
 
-if [ -z ${MANAGER_IDENTITY_FILE} ]; then
+if [ -z "${MANAGER_IDENTITY_FILE}" ]; then
     echo -e "missing --manager-identity-file\n"
+    print_usage
+    exit 1
+fi
+
+if [ ! -w "${MANAGER_IDENTITY_FILE}" ]; then
+    echo -e "cannot write to file ${MANAGER_IDENTITY_FILE}\n"
     print_usage
     exit 1
 fi
diff --git a/dist/scripts/scyllamgr_ssh_test b/dist/scripts/scyllamgr_ssh_test
--- a/dist/scripts/scyllamgr_ssh_test
+++ b/dist/scripts/scyllamgr_ssh_test
@@ -56,14 +56,20 @@ if [ $# == 0 ]; then
     exit 1
 fi
 
-if [ -z ${SSH_USER} ]; then
+if [ -z "${SSH_USER}" ]; then
     echo -e "missing --user\n"
     print_usage
     exit 1
 fi
 
-if [ -z ${SSH_IDENTITY_FILE} ]; then
+if [ -z "${SSH_IDENTITY_FILE}" ]; then
     echo -e "missing --identity-file\n"
+    print_usage
+    exit 1
+fi
+
+if [ ! -f "${SSH_IDENTITY_FILE}" -o ! -r "${SSH_IDENTITY_FILE}" ]; then
+    echo -e "cannot read file ${SSH_IDENTITY_FILE}\n"
     print_usage
     exit 1
 fi
